CREATE TABLE credit_customers AS
SELECT *
FROM stg_credit_customers;

UPDATE credit_customers
SET EDUCATION = 4
WHERE EDUCATION IN (0,5,6);

SELECT EDUCATION, COUNT(*)
FROM credit_customers
GROUP BY EDUCATION
ORDER BY EDUCATION;

UPDATE credit_customers
SET MARRIAGE = 3
WHERE MARRIAGE = 0;

SELECT MARRIAGE,COUNT(*) FROM credit_customers
GROUP BY MARRIAGE
ORDER BY MARRIAGE;